packages:
  - apps/*
  - packages/**

catalog:
  lucide-react: 0.525.0
  next: ^15
  react: ^19
  react-dom: ^19
  react-markdown: ^10
  typescript: ^5
  eslint: ^9.29.0
  gsap: ^3.11.5
  '@types/node': ^24
  '@types/react': ^19
  '@types/react-dom': ^19
