import { VisualArchive } from '../types'

export const VISUAL_ARCHIVE = {
  id: 'visual-archive',
  title: 'Resignificando Lo Cotidiano',
  subTitle: 'Galería de imágenes de la Villa Covico de Coquimbo',
  cards: {
    photos: {
      id: 'photos',
      title: 'Fotografías',
      gallery: [
        {
          src: '/villacovico/sections/visual-archive/photos/JORGE ORACIO PEREZ 1.0.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 903,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/JORGE ORACIO PEREZ 1.1.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 883,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/JORGE ORACIO PEREZ 1.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 942,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/JUAN CARLOS VALENCIA 1 -02.webp',
          alt: 'Fotografía placeholder',
          width: 944,
          height: 1308,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/JUAN CARLOS VALENCIA 1 -03.webp',
          alt: 'Fotografía placeholder',
          width: 1334,
          height: 913,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/JUAN CARLOS VALENCIA 1 -04.webp',
          alt: 'Fotografía placeholder',
          width: 1243,
          height: 1106,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 09.webp',
          alt: 'Fotografía placeholder',
          width: 1899,
          height: 1367,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 2.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 1108,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 5.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 1026,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 533.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 1003,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 6-01-01.webp',
          alt: 'Fotografía placeholder',
          width: 885,
          height: 600,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 6-01-02.webp',
          alt: 'Fotografía placeholder',
          width: 783,
          height: 1073,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 6-01-03.webp',
          alt: 'Fotografía placeholder',
          width: 1206,
          height: 840,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/PATRICIA ROMERO 7.webp',
          alt: 'Fotografía placeholder',
          width: 1587,
          height: 1039,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0001.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 919,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0002.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 928,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0003.webp',
          alt: 'Fotografía placeholder',
          width: 1015,
          height: 644,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0004.webp',
          alt: 'Fotografía placeholder',
          width: 1032,
          height: 653,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0005.webp',
          alt: 'Fotografía placeholder',
          width: 1010,
          height: 657,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0006.webp',
          alt: 'Fotografía placeholder',
          width: 1336,
          height: 2027,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0007.webp',
          alt: 'Fotografía placeholder',
          width: 1440,
          height: 924,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0008.webp',
          alt: 'Fotografía placeholder',
          width: 1050,
          height: 685,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0009.webp',
          alt: 'Fotografía placeholder',
          width: 1036,
          height: 694,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0010.webp',
          alt: 'Fotografía placeholder',
          width: 1022,
          height: 682,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0011.webp',
          alt: 'Fotografía placeholder',
          width: 1030,
          height: 638,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0012.webp',
          alt: 'Fotografía placeholder',
          width: 1040,
          height: 657,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/foto escaner 0013.webp',
          alt: 'Fotografía placeholder',
          width: 1024,
          height: 662,
        },
        {
          src: '/villacovico/sections/visual-archive/photos/niños bandera.webp',
          alt: 'Fotografía placeholder',
          width: 698,
          height: 1440,
        },
      ],
    },
    'aerial-images': {
      id: 'aerial-images',
      title: 'Fotografías Aéreas',
      gallery: [],
    },
    illustrations: {
      id: 'illustrations',
      title: 'Ilustraciones',
      gallery: [
        {
          src: '/villacovico/sections/visual-archive/illustrations/Carlos Echeverria.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 720,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/Carlos Jorquera.webp',
          alt: 'Ilustración placeholder',
          width: 1095,
          height: 1440,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/Marin vicuña.webp',
          alt: 'Ilustración placeholder',
          width: 1335,
          height: 1080,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/alfonso rojas arbol.webp',
          alt: 'Ilustración placeholder',
          width: 518,
          height: 1440,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/alfonso rojas.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 720,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/boceto.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 658,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/estacion.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 414,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/ferrocarriles.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 934,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/hector cabezas.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 663,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/jaime jimenez.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 642,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/juancarlos.webp',
          alt: 'Ilustración placeholder',
          width: 982,
          height: 1440,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/lolero.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 880,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/lugares al final de los relatos.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 720,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/monica carmen.webp',
          alt: 'Ilustración placeholder',
          width: 1080,
          height: 1305,
        },
        {
          src: '/villacovico/sections/visual-archive/illustrations/scout.webp',
          alt: 'Ilustración placeholder',
          width: 1440,
          height: 867,
        },
      ],
    },
  },
} satisfies VisualArchive
